# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
  deploy:
    # Chạy job này trên phiên bản Ubuntu mới nhất
    runs-on: ubuntu-latest
    # Job này phụ thuộc vào một job khác có tên là 'build'
    needs: build
    # Chỉ chạy job này khi có push lên nhánh 'main'
    if: github.ref == 'refs/heads/main'

    steps:
      # Bước 1: Checkout mã nguồn từ repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Bước 2: Triển khai lên môi trường Production
      - name: Deploy to Production
        run: |
          echo "Starting deployment..."
          # Thay thế dòng echo này bằng các lệnh triển khai thực tế, ví dụ:
          # ssh user@your-server "cd /path/to/project && git pull && systemctl restart your-service"
